/* generated by Svelte vX.Y.Z */
import { addResizeListener, assign, createElement, detachNode, init, insertNode, noop, proto } from "svelte/shared.js";

function create_main_fragment(component, ctx) {
	var div, div_resize_listener;

	function div_resize_handler() {
		component.set({ w: div.offsetWidth, h: offsetHeight });
	}

	return {
		c: function create() {
			div = createElement("div");
			div.textContent = "some content";
		},

		h: function hydrate() {
			div_resize_listener = addResizeListener(div, div_resize_handler);
			component._beforecreate.push(div_resize_handler);
		},

		m: function mount(target, anchor) {
			insertNode(div, target, anchor);
		},

		p: noop,

		u: function unmount() {
			div_resize_listener.cancel();
			detachNode(div);
		},

		d: noop
	};
}

function SvelteComponent(options) {
	init(this, options);
	this._state = assign({}, options.data);

	this._fragment = create_main_fragment(this, this._state);

	if (options.target) {
		this._fragment.c();
		this._mount(options.target, options.anchor);
	}
}

assign(SvelteComponent.prototype, proto);
export default SvelteComponent;