/* generated by Svelte vX.Y.Z */
import { assign, callAll, init, noop, proto } from "svelte/shared.js";

function data_1() {
	return {
	foo: 'bar'
};
}

function oncreate() {
	alert(JSON.stringify(data()));
};

function create_main_fragment(component, state) {

	return {
		c: noop,

		m: noop,

		p: noop,

		u: noop,

		d: noop
	};
}

function SvelteComponent(options) {
	init(this, options);
	this._state = assign(data_1(), options.data);

	var self = this;
	var _oncreate = function() {
		var changed = {  };
		oncreate.call(self);
		self.fire("update", { changed: changed, current: self._state });
	};

	if (!options.root) {
		this._oncreate = [];
	}

	this._fragment = create_main_fragment(this, this._state);

	this.root._oncreate.push(_oncreate);

	if (options.target) {
		this._fragment.c();
		this._mount(options.target, options.anchor);

		callAll(this._oncreate);
	}
}

assign(SvelteComponent.prototype, proto);
export default SvelteComponent;