/* generated by Svelte vX.Y.Z */
import { SvelteComponent as SvelteComponent_1, addListener, createElement, detachNode, init, insert, noop, safe_not_equal } from "svelte/internal";

function create_fragment(ctx) {
	var input, dispose;

	return {
		c() {
			input = createElement("input");
			dispose = addListener(input, "input", make_uppercase);
		},

		m(target, anchor) {
			insert(target, input, anchor);
		},

		p: noop,
		i: noop,
		o: noop,

		d(detach) {
			if (detach) {
				detachNode(input);
			}

			dispose();
		}
	};
}

function make_uppercase() {
	this.value = this.value.toUpperCase();
}

class SvelteComponent extends SvelteComponent_1 {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal);
	}
}

export default SvelteComponent;
