/* generated by Svelte vX.Y.Z */
import { addListener, assign, createElement, detachNode, init, insertNode, proto, removeListener, setAttribute } from "svelte/shared.js";

function create_main_fragment(component, ctx) {
	var input;

	function input_change_handler() {
		component.set({ foo: input.checked });
	}

	return {
		c() {
			input = createElement("input");
			addListener(input, "change", input_change_handler);
			setAttribute(input, "type", "checkbox");
		},

		m(target, anchor) {
			insertNode(input, target, anchor);

			input.checked = ctx.foo;
		},

		p(changed, ctx) {
			input.checked = ctx.foo;
		},

		d(detach) {
			if (detach) {
				detachNode(input);
			}

			removeListener(input, "change", input_change_handler);
		}
	};
}

function SvelteComponent(options) {
	init(this, options);
	this._state = assign({}, options.data);
	this._intro = true;

	this._fragment = create_main_fragment(this, this._state);

	if (options.target) {
		this._fragment.c();
		this._mount(options.target, options.anchor, true);
	}
}

assign(SvelteComponent.prototype, proto);
export default SvelteComponent;