/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	add_render_callback,
	detach,
	element,
	init,
	insert,
	listen,
	noop,
	raf,
	run_all,
	safe_not_equal
} from "svelte/internal";

function create_fragment(ctx) {
	let video;
	let video_updating = false;
	let video_animationframe;
	let dispose;

	function video_timeupdate_handler() {
		cancelAnimationFrame(video_animationframe);

		if (!video.paused) {
			video_animationframe = raf(video_timeupdate_handler);
			video_updating = true;
		}

		ctx.video_timeupdate_handler.call(video);
	}

	return {
		c() {
			video = element("video");
			if (ctx.videoHeight === void 0 || ctx.videoWidth === void 0) add_render_callback(() => ctx.video_resize_handler.call(video));

			dispose = [
				listen(video, "timeupdate", video_timeupdate_handler),
				listen(video, "resize", ctx.video_resize_handler)
			];
		},
		m(target, anchor) {
			insert(target, video, anchor);
		},
		p(changed, ctx) {
			if (!video_updating && changed.currentTime && !isNaN(ctx.currentTime)) {
				video.currentTime = ctx.currentTime;
			}

			video_updating = false;
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(video);
			run_all(dispose);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { currentTime } = $$props;
	let { videoHeight } = $$props;
	let { videoWidth } = $$props;

	function video_timeupdate_handler() {
		currentTime = this.currentTime;
		$$invalidate("currentTime", currentTime);
	}

	function video_resize_handler() {
		videoHeight = this.videoHeight;
		videoWidth = this.videoWidth;
		$$invalidate("videoHeight", videoHeight);
		$$invalidate("videoWidth", videoWidth);
	}

	$$self.$set = $$props => {
		if ("currentTime" in $$props) $$invalidate("currentTime", currentTime = $$props.currentTime);
		if ("videoHeight" in $$props) $$invalidate("videoHeight", videoHeight = $$props.videoHeight);
		if ("videoWidth" in $$props) $$invalidate("videoWidth", videoWidth = $$props.videoWidth);
	};

	return {
		currentTime,
		videoHeight,
		videoWidth,
		video_timeupdate_handler,
		video_resize_handler
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			currentTime: 0,
			videoHeight: 0,
			videoWidth: 0
		});
	}
}

export default Component;