/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	append,
	element,
	init,
	mount_component,
	noop,
	safe_not_equal
} from "svelte/internal";

function add_css() {
	var style = element("style");
	style.id = 'svelte-1rk2jaa-style';
	style.textContent = ".custom.svelte-1rk2jaa{color:'blue'}";
	append(document.head, style);
}

function create_fragment(ctx) {
	var current;

	var nested = new ctx.Nested({
		props: { class: "custom svelte-1rk2jaa" }
	});

	return {
		c() {
			nested.$$.fragment.c();
		},

		m(target, anchor) {
			mount_component(nested, target, anchor);
			current = true;
		},

		p: noop,

		i(local) {
			if (current) return;
			nested.$$.fragment.i(local);

			current = true;
		},

		o(local) {
			nested.$$.fragment.o(local);
			current = false;
		},

		d(detaching) {
			nested.$destroy(detaching);
		}
	};
}

function instance($$self) {
	const Nested = window.Nested;

	return { Nested };
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		if (!document.getElementById("svelte-1rk2jaa-style")) add_css();
		init(this, options, instance, create_fragment, safe_not_equal, []);
	}
}

export default Component;
