/* input.svelte generated by Svelte vx.x.x */
import {
	SvelteComponent,
	append_styles,
	attr,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal
} from "svelte/internal";

import "svelte/internal/disclose-version";

function add_css(target) {
	append_styles(target, "svelte-1g8ykrs", "span.svelte-1g8ykrs{--external_code-var:1px}");
}

function create_fragment(ctx) {
	let span;

	return {
		c() {
			span = element("span");
			span.textContent = "Hello world";
			attr(span, "class", "svelte-1g8ykrs");
		},
		m(target, anchor) {
			insert(target, span, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) {
				detach(span);
			}
		}
	};
}

class Input extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {}, add_css);
	}
}

export default Input;
//# sourceMappingURL=_actual.js.map