/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	init,
	mount_component,
	noop,
	safe_not_equal
} from "svelte/internal";
import LazyLoad from "./LazyLoad.svelte";

function create_fragment(ctx) {
	var current;

	var lazyload = new LazyLoad({ props: { load: func } });

	return {
		c() {
			lazyload.$$.fragment.c();
		},

		m(target, anchor) {
			mount_component(lazyload, target, anchor);
			current = true;
		},

		p: noop,

		i(local) {
			if (current) return;
			lazyload.$$.fragment.i(local);

			current = true;
		},

		o(local) {
			lazyload.$$.fragment.o(local);
			current = false;
		},

		d(detaching) {
			lazyload.$destroy(detaching);
		}
	};
}

function func() {
	return import('./Foo.svelte');
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, []);
	}
}

export default Component;