/* index.svelte.js generated by Svelte VERSION */
import * as $ from "svelte/internal/client";

let a = $.source(1);
let b = $.source(2);

export function update(array) {
	(
		$.set(a, $.proxy(array[0])),
		$.set(b, $.proxy(array[1]))
	);
}