/* This file is generated by scripts/process-messages/index.js. Do not edit! */

export * from '../shared/errors.js';

/**
 * The node API `AsyncLocalStorage` is not available, but is required to use async server rendering.
 * @param {void} values
 * @returns {never}
 */
export function async_local_storage_unavailable(values) {
	const error = new Error(`${'async_local_storage_unavailable'}\n${`The node API \`AsyncLocalStorage\` is not available, but is required to use async server rendering.`}\nhttps://svelte.dev/e/${'async_local_storage_unavailable'}`);
	error.name = 'Svelte error';
	throw error;
}

/**
 * Encountered asynchronous work while rendering synchronously.
 * @param {void} values
 * @returns {never}
 */
export function await_invalid(values) {
	const error = new Error(`${'await_invalid'}\n${`Encountered asynchronous work while rendering synchronously.`}\nhttps://svelte.dev/e/${'await_invalid'}`);
	error.name = 'Svelte error';
	throw error;
}

/**
 * `<svelte:element this="%tag%">` is not a valid element name — the element will not be rendered
 * @param {{ "tag": string }} values
 * @returns {never}
 */
export function dynamic_element_invalid_tag(values) {
	const error = new Error(`${'dynamic_element_invalid_tag'}\n${`\`<svelte:element this="${values.tag}">\` is not a valid element name — the element will not be rendered`}\nhttps://svelte.dev/e/${'dynamic_element_invalid_tag'}`);
	error.name = 'Svelte error';
	throw error;
}

/**
 * The `html` property of server render results has been deprecated. Use `body` instead.
 * @param {void} values
 * @returns {never}
 */
export function html_deprecated(values) {
	const error = new Error(`${'html_deprecated'}\n${`The \`html\` property of server render results has been deprecated. Use \`body\` instead.`}\nhttps://svelte.dev/e/${'html_deprecated'}`);
	error.name = 'Svelte error';
	throw error;
}

/**
 * Attempted to set `hydratable` with key `%key%` twice with different values.

%stack%
 * @param {{ "key": string; "stack": string }} values
 * @returns {never}
 */
export function hydratable_clobbering(values) {
	const error = new Error(`${'hydratable_clobbering'}\n${`Attempted to set \`hydratable\` with key \`${values.key}\` twice with different values.

${values.stack}`}\nhttps://svelte.dev/e/${'hydratable_clobbering'}`);
	error.name = 'Svelte error';
	throw error;
}

/**
 * Failed to serialize `hydratable` data for key `%key%`.

`hydratable` can serialize anything [`uneval` from `devalue`](https://npmjs.com/package/uneval) can, plus Promises.

Cause:
%stack%
 * @param {{ "key": string; "stack": string }} values
 * @returns {never}
 */
export function hydratable_serialization_failed(values) {
	const error = new Error(`${'hydratable_serialization_failed'}\n${`Failed to serialize \`hydratable\` data for key \`${values.key}\`.

\`hydratable\` can serialize anything [\`uneval\` from \`devalue\`](https://npmjs.com/package/uneval) can, plus Promises.

Cause:
${values.stack}`}\nhttps://svelte.dev/e/${'hydratable_serialization_failed'}`);
	error.name = 'Svelte error';
	throw error;
}

/**
 * `csp.nonce` was set while `csp.hash` was `true`. These options cannot be used simultaneously.
 * @param {void} values
 * @returns {never}
 */
export function invalid_csp(values) {
	const error = new Error(`${'invalid_csp'}\n${`\`csp.nonce\` was set while \`csp.hash\` was \`true\`. These options cannot be used simultaneously.`}\nhttps://svelte.dev/e/${'invalid_csp'}`);
	error.name = 'Svelte error';
	throw error;
}

/**
 * The `idPrefix` option cannot include `--`.
 * @param {void} values
 * @returns {never}
 */
export function invalid_id_prefix(values) {
	const error = new Error(`${'invalid_id_prefix'}\n${`The \`idPrefix\` option cannot include \`--\`.`}\nhttps://svelte.dev/e/${'invalid_id_prefix'}`);
	error.name = 'Svelte error';
	throw error;
}

/**
 * `%name%(...)` is not available on the server
 * @param {{ "name": string }} values
 * @returns {never}
 */
export function lifecycle_function_unavailable(values) {
	const error = new Error(`${'lifecycle_function_unavailable'}\n${`\`${values.name}(...)\` is not available on the server`}\nhttps://svelte.dev/e/${'lifecycle_function_unavailable'}`);
	error.name = 'Svelte error';
	throw error;
}

/**
 * Could not resolve `render` context.
 * @param {void} values
 * @returns {never}
 */
export function server_context_required(values) {
	const error = new Error(`${'server_context_required'}\n${`Could not resolve \`render\` context.`}\nhttps://svelte.dev/e/${'server_context_required'}`);
	error.name = 'Svelte error';
	throw error;
}
