/* This file is generated by scripts/process-messages/index.js. Do not edit! */

import { DEV } from 'esm-env';

var bold = 'font-weight: bold';
var normal = 'font-weight: normal';

/**
 * Part of the data added to `Warp` instances was not used during the render, so the response was delayed until it resolved.
 */
export function unresolved_warp() {
	if (DEV) {
		console.warn(`%c[svelte] unresolved_warp\n%cPart of the data added to \`Warp\` instances was not used during the render, so the response was delayed until it resolved.\nhttps://svelte.dev/e/unresolved_warp`, bold, normal);
	} else {
		console.warn(`https://svelte.dev/e/unresolved_warp`);
	}
}