/* generated by Svelte vX.Y.Z */
import { append, assign, createElement, detachNode, init, noop, proto } from "svelte/shared.js";

function create_main_fragment(component, ctx) {
	var meta, meta_1;

	return {
		c() {
			meta = createElement("meta");
			meta_1 = createElement("meta");
			meta.name = "twitter:creator";
			meta.content = "@sveltejs";
			meta_1.name = "twitter:title";
			meta_1.content = "Svelte";
		},

		m(target, anchor) {
			append(document.head, meta);
			append(document.head, meta_1);
		},

		p: noop,

		d(detach) {
			detachNode(meta);
			detachNode(meta_1);
		}
	};
}

function SvelteComponent(options) {
	init(this, options);
	this._state = assign({}, options.data);
	this._intro = true;

	this._fragment = create_main_fragment(this, this._state);

	if (options.target) {
		this._fragment.c();
		this._mount(options.target, options.anchor);
	}
}

assign(SvelteComponent.prototype, proto);
export default SvelteComponent;