/* generated by Svelte vX.Y.Z */
import { assign, init, noop, proto } from "svelte/shared.js";

function create_main_fragment(component, state) {
	var title_value;

	document.title = title_value = "a " + state.custom + " title";

	return {
		c: noop,

		m: noop,

		p: function update(changed, state) {
			if ((changed.custom) && title_value !== (title_value = "a " + state.custom + " title")) {
				document.title = title_value;
			}
		},

		u: noop,

		d: noop
	};
}

function SvelteComponent(options) {
	init(this, options);
	this._state = assign({}, options.data);

	this._fragment = create_main_fragment(this, this._state);

	if (options.target) {
		this._fragment.c();
		this._mount(options.target, options.anchor || null);
	}
}

assign(SvelteComponent.prototype, proto);
export default SvelteComponent;