/* This file is generated by scripts/process-messages/index.js. Do not edit! */

import { DEV } from 'esm-env';

export * from '../shared/errors.js';

/**
 * Cannot create a `$derived(...)` with an `await` expression outside of an effect tree
 * @param {void} values
 * @returns {never}
 */
export function async_derived_orphan(values) {
	if (DEV) {
		const error = new Error(`${'async_derived_orphan'}\n${`Cannot create a \`$derived(...)\` with an \`await\` expression outside of an effect tree`}\nhttps://svelte.dev/e/${'async_derived_orphan'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'async_derived_orphan'}`);
	}
}

/**
 * Using `bind:value` together with a checkbox input is not allowed. Use `bind:checked` instead
 * @param {void} values
 * @returns {never}
 */
export function bind_invalid_checkbox_value(values) {
	if (DEV) {
		const error = new Error(`${'bind_invalid_checkbox_value'}\n${`Using \`bind:value\` together with a checkbox input is not allowed. Use \`bind:checked\` instead`}\nhttps://svelte.dev/e/${'bind_invalid_checkbox_value'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'bind_invalid_checkbox_value'}`);
	}
}

/**
 * Component %component% has an export named `%key%` that a consumer component is trying to access using `bind:%key%`, which is disallowed. Instead, use `bind:this` (e.g. `<%name% bind:this={component} />`) and then access the property on the bound component instance (e.g. `component.%key%`)
 * @param {{ "component": string, "key": string, "name": string }} values
 * @returns {never}
 */
export function bind_invalid_export(values) {
	if (DEV) {
		const error = new Error(`${'bind_invalid_export'}\n${`Component ${values.component} has an export named \`${values.key}\` that a consumer component is trying to access using \`bind:${values.key}\`, which is disallowed. Instead, use \`bind:this\` (e.g. \`<${values.name} bind:this={component} />\`) and then access the property on the bound component instance (e.g. \`component.${values.key}\`)`}\nhttps://svelte.dev/e/${'bind_invalid_export'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'bind_invalid_export'}`);
	}
}

/**
 * A component is attempting to bind to a non-bindable property `%key%` belonging to %component% (i.e. `<%name% bind:%key%={...}>`). To mark a property as bindable: `let { %key% = $bindable() } = $props()`
 * @param {{ "key": string, "component": string, "name": string }} values
 * @returns {never}
 */
export function bind_not_bindable(values) {
	if (DEV) {
		const error = new Error(`${'bind_not_bindable'}\n${`A component is attempting to bind to a non-bindable property \`${values.key}\` belonging to ${values.component} (i.e. \`<${values.name} bind:${values.key}={...}>\`). To mark a property as bindable: \`let { ${values.key} = $bindable() } = $props()\``}\nhttps://svelte.dev/e/${'bind_not_bindable'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'bind_not_bindable'}`);
	}
}

/**
 * Calling `%method%` on a component instance (of %component%) is no longer valid in Svelte 5
 * @param {{ "method": string, "component": string }} values
 * @returns {never}
 */
export function component_api_changed(values) {
	if (DEV) {
		const error = new Error(`${'component_api_changed'}\n${`Calling \`${values.method}\` on a component instance (of ${values.component}) is no longer valid in Svelte 5`}\nhttps://svelte.dev/e/${'component_api_changed'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'component_api_changed'}`);
	}
}

/**
 * Attempted to instantiate %component% with `new %name%`, which is no longer valid in Svelte 5. If this component is not under your control, set the `compatibility.componentApi` compiler option to `4` to keep it working.
 * @param {{ "component": string, "name": string }} values
 * @returns {never}
 */
export function component_api_invalid_new(values) {
	if (DEV) {
		const error = new Error(`${'component_api_invalid_new'}\n${`Attempted to instantiate ${values.component} with \`new ${values.name}\`, which is no longer valid in Svelte 5. If this component is not under your control, set the \`compatibility.componentApi\` compiler option to \`4\` to keep it working.`}\nhttps://svelte.dev/e/${'component_api_invalid_new'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'component_api_invalid_new'}`);
	}
}

/**
 * A derived value cannot reference itself recursively
 * @param {void} values
 * @returns {never}
 */
export function derived_references_self(values) {
	if (DEV) {
		const error = new Error(`${'derived_references_self'}\n${`A derived value cannot reference itself recursively`}\nhttps://svelte.dev/e/${'derived_references_self'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'derived_references_self'}`);
	}
}

/**
 * Keyed each block has duplicate key at indexes %a% and %b%
 * @param {{ "a": string, "b": string } | { "value": string, "a": string, "b": string }} values
 * @returns {never}
 */
export function each_key_duplicate(values) {
	if (DEV) {
		const error = new Error(`${'each_key_duplicate'}\n${(values?.b !== undefined ? `Keyed each block has duplicate key \`${values.value}\` at indexes ${values.a} and ${values.b}` : `Keyed each block has duplicate key at indexes ${values.a} and ${values.b}`)}\nhttps://svelte.dev/e/${'each_key_duplicate'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'each_key_duplicate'}`);
	}
}

/**
 * Keyed each block has key that is not idempotent — the key for item at index %index% was `%a%` but is now `%b%`. Keys must be the same each time for a given item
 * @param {{ "index": string, "a": string, "b": string }} values
 * @returns {never}
 */
export function each_key_volatile(values) {
	if (DEV) {
		const error = new Error(`${'each_key_volatile'}\n${`Keyed each block has key that is not idempotent — the key for item at index ${values.index} was \`${values.a}\` but is now \`${values.b}\`. Keys must be the same each time for a given item`}\nhttps://svelte.dev/e/${'each_key_volatile'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'each_key_volatile'}`);
	}
}

/**
 * `%rune%` cannot be used inside an effect cleanup function
 * @param {{ "rune": string }} values
 * @returns {never}
 */
export function effect_in_teardown(values) {
	if (DEV) {
		const error = new Error(`${'effect_in_teardown'}\n${`\`${values.rune}\` cannot be used inside an effect cleanup function`}\nhttps://svelte.dev/e/${'effect_in_teardown'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'effect_in_teardown'}`);
	}
}

/**
 * Effect cannot be created inside a `$derived` value that was not itself created inside an effect
 * @param {void} values
 * @returns {never}
 */
export function effect_in_unowned_derived(values) {
	if (DEV) {
		const error = new Error(`${'effect_in_unowned_derived'}\n${`Effect cannot be created inside a \`$derived\` value that was not itself created inside an effect`}\nhttps://svelte.dev/e/${'effect_in_unowned_derived'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'effect_in_unowned_derived'}`);
	}
}

/**
 * `%rune%` can only be used inside an effect (e.g. during component initialisation)
 * @param {{ "rune": string }} values
 * @returns {never}
 */
export function effect_orphan(values) {
	if (DEV) {
		const error = new Error(`${'effect_orphan'}\n${`\`${values.rune}\` can only be used inside an effect (e.g. during component initialisation)`}\nhttps://svelte.dev/e/${'effect_orphan'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'effect_orphan'}`);
	}
}

/**
 * `$effect.pending()` can only be called inside an effect or derived
 * @param {void} values
 * @returns {never}
 */
export function effect_pending_outside_reaction(values) {
	if (DEV) {
		const error = new Error(`${'effect_pending_outside_reaction'}\n${`\`$effect.pending()\` can only be called inside an effect or derived`}\nhttps://svelte.dev/e/${'effect_pending_outside_reaction'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'effect_pending_outside_reaction'}`);
	}
}

/**
 * Maximum update depth exceeded. This typically indicates that an effect reads and writes the same piece of state
 * @param {void} values
 * @returns {never}
 */
export function effect_update_depth_exceeded(values) {
	if (DEV) {
		const error = new Error(`${'effect_update_depth_exceeded'}\n${`Maximum update depth exceeded. This typically indicates that an effect reads and writes the same piece of state`}\nhttps://svelte.dev/e/${'effect_update_depth_exceeded'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'effect_update_depth_exceeded'}`);
	}
}

/**
 * Cannot use `flushSync` inside an effect
 * @param {void} values
 * @returns {never}
 */
export function flush_sync_in_effect(values) {
	if (DEV) {
		const error = new Error(`${'flush_sync_in_effect'}\n${`Cannot use \`flushSync\` inside an effect`}\nhttps://svelte.dev/e/${'flush_sync_in_effect'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'flush_sync_in_effect'}`);
	}
}

/**
 * Cannot commit a fork that was already discarded
 * @param {void} values
 * @returns {never}
 */
export function fork_discarded(values) {
	if (DEV) {
		const error = new Error(`${'fork_discarded'}\n${`Cannot commit a fork that was already discarded`}\nhttps://svelte.dev/e/${'fork_discarded'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'fork_discarded'}`);
	}
}

/**
 * Cannot create a fork inside an effect or when state changes are pending
 * @param {void} values
 * @returns {never}
 */
export function fork_timing(values) {
	if (DEV) {
		const error = new Error(`${'fork_timing'}\n${`Cannot create a fork inside an effect or when state changes are pending`}\nhttps://svelte.dev/e/${'fork_timing'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'fork_timing'}`);
	}
}

/**
 * `getAbortSignal()` can only be called inside an effect or derived
 * @param {void} values
 * @returns {never}
 */
export function get_abort_signal_outside_reaction(values) {
	if (DEV) {
		const error = new Error(`${'get_abort_signal_outside_reaction'}\n${`\`getAbortSignal()\` can only be called inside an effect or derived`}\nhttps://svelte.dev/e/${'get_abort_signal_outside_reaction'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'get_abort_signal_outside_reaction'}`);
	}
}

/**
 * Expected to find a hydratable with key `%key%` during hydration, but did not.
 * @param {{ "key": string }} values
 * @returns {never}
 */
export function hydratable_missing_but_required(values) {
	if (DEV) {
		const error = new Error(`${'hydratable_missing_but_required'}\n${`Expected to find a hydratable with key \`${values.key}\` during hydration, but did not.`}\nhttps://svelte.dev/e/${'hydratable_missing_but_required'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'hydratable_missing_but_required'}`);
	}
}

/**
 * Failed to hydrate the application
 * @param {void} values
 * @returns {never}
 */
export function hydration_failed(values) {
	if (DEV) {
		const error = new Error(`${'hydration_failed'}\n${`Failed to hydrate the application`}\nhttps://svelte.dev/e/${'hydration_failed'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'hydration_failed'}`);
	}
}

/**
 * Could not `{@render}` snippet due to the expression being `null` or `undefined`. Consider using optional chaining `{@render snippet?.()}`
 * @param {void} values
 * @returns {never}
 */
export function invalid_snippet(values) {
	if (DEV) {
		const error = new Error(`${'invalid_snippet'}\n${`Could not \`{@render}\` snippet due to the expression being \`null\` or \`undefined\`. Consider using optional chaining \`{@render snippet?.()}\``}\nhttps://svelte.dev/e/${'invalid_snippet'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'invalid_snippet'}`);
	}
}

/**
 * `%name%(...)` cannot be used in runes mode
 * @param {{ "name": string }} values
 * @returns {never}
 */
export function lifecycle_legacy_only(values) {
	if (DEV) {
		const error = new Error(`${'lifecycle_legacy_only'}\n${`\`${values.name}(...)\` cannot be used in runes mode`}\nhttps://svelte.dev/e/${'lifecycle_legacy_only'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'lifecycle_legacy_only'}`);
	}
}

/**
 * Cannot do `bind:%key%={undefined}` when `%key%` has a fallback value
 * @param {{ "key": string }} values
 * @returns {never}
 */
export function props_invalid_value(values) {
	if (DEV) {
		const error = new Error(`${'props_invalid_value'}\n${`Cannot do \`bind:${values.key}={undefined}\` when \`${values.key}\` has a fallback value`}\nhttps://svelte.dev/e/${'props_invalid_value'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'props_invalid_value'}`);
	}
}

/**
 * Rest element properties of `$props()` such as `%property%` are readonly
 * @param {{ "property": string }} values
 * @returns {never}
 */
export function props_rest_readonly(values) {
	if (DEV) {
		const error = new Error(`${'props_rest_readonly'}\n${`Rest element properties of \`$props()\` such as \`${values.property}\` are readonly`}\nhttps://svelte.dev/e/${'props_rest_readonly'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'props_rest_readonly'}`);
	}
}

/**
 * The `%rune%` rune is only available inside `.svelte` and `.svelte.js/ts` files
 * @param {{ "rune": string }} values
 * @returns {never}
 */
export function rune_outside_svelte(values) {
	if (DEV) {
		const error = new Error(`${'rune_outside_svelte'}\n${`The \`${values.rune}\` rune is only available inside \`.svelte\` and \`.svelte.js/ts\` files`}\nhttps://svelte.dev/e/${'rune_outside_svelte'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'rune_outside_svelte'}`);
	}
}

/**
 * Property descriptors defined on `$state` objects must contain `value` and always be `enumerable`, `configurable` and `writable`.
 * @param {void} values
 * @returns {never}
 */
export function state_descriptors_fixed(values) {
	if (DEV) {
		const error = new Error(`${'state_descriptors_fixed'}\n${`Property descriptors defined on \`$state\` objects must contain \`value\` and always be \`enumerable\`, \`configurable\` and \`writable\`.`}\nhttps://svelte.dev/e/${'state_descriptors_fixed'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'state_descriptors_fixed'}`);
	}
}

/**
 * Cannot set prototype of `$state` object
 * @param {void} values
 * @returns {never}
 */
export function state_prototype_fixed(values) {
	if (DEV) {
		const error = new Error(`${'state_prototype_fixed'}\n${`Cannot set prototype of \`$state\` object`}\nhttps://svelte.dev/e/${'state_prototype_fixed'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'state_prototype_fixed'}`);
	}
}

/**
 * Updating state inside `$derived(...)`, `$inspect(...)` or a template expression is forbidden. If the value should not be reactive, declare it without `$state`
 * @param {void} values
 * @returns {never}
 */
export function state_unsafe_mutation(values) {
	if (DEV) {
		const error = new Error(`${'state_unsafe_mutation'}\n${`Updating state inside \`$derived(...)\`, \`$inspect(...)\` or a template expression is forbidden. If the value should not be reactive, declare it without \`$state\``}\nhttps://svelte.dev/e/${'state_unsafe_mutation'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'state_unsafe_mutation'}`);
	}
}

/**
 * A `<svelte:boundary>` `reset` function cannot be called while an error is still being handled
 * @param {void} values
 * @returns {never}
 */
export function svelte_boundary_reset_onerror(values) {
	if (DEV) {
		const error = new Error(`${'svelte_boundary_reset_onerror'}\n${`A \`<svelte:boundary>\` \`reset\` function cannot be called while an error is still being handled`}\nhttps://svelte.dev/e/${'svelte_boundary_reset_onerror'}`);
		error.name = 'Svelte error';
		throw error;
	} else {
		throw new Error(`https://svelte.dev/e/${'svelte_boundary_reset_onerror'}`);
	}
}
