import fs from 'node:fs';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import { createBundle } from 'dts-buddy';

const dir = fileURLToPath(new URL('..', import.meta.url));
const pkg = JSON.parse(fs.readFileSync(`${dir}/package.json`, 'utf-8'));

// -------------------------------------------------------------
// Legacy entry-point shims
// -------------------------------------------------------------
for (const name of ['action', 'animate', 'easing', 'motion', 'store', 'transition', 'legacy']) {
	fs.writeFileSync(`${dir}/${name}.d.ts`, "import './types/index.js';\n");
}

fs.writeFileSync(`${dir}/index.d.ts`, "import './types/index.js';\n");
fs.writeFileSync(`${dir}/compiler.d.ts`, "import './types/index.js';\n");

// -------------------------------------------------------------
// Legacy compiler shims
// -------------------------------------------------------------
fs.mkdirSync(`${dir}/types/compiler`, { recursive: true });
fs.writeFileSync(`${dir}/types/compiler/preprocess.d.ts`, "import '../index.js';\n");
fs.writeFileSync(`${dir}/types/compiler/interfaces.d.ts`, "import '../index.js';\n");

// -------------------------------------------------------------
// Generate bundled ambient types
// -------------------------------------------------------------
await createBundle({
	output: `${dir}/types/index.d.ts`,
	compilerOptions: {
		stripInternal: true,
		paths: Object.fromEntries(
			Object.entries(pkg.imports).map(([key, value]) => [key, [value.types ?? value.default ?? value]])
		)
	},
	modules: {
		[pkg.name]: `${dir}/src/index.d.ts`,
		[`${pkg.name}/action`]: `${dir}/src/action/public.d.ts`,
		[`${pkg.name}/animate`]: `${dir}/src/animate/public.d.ts`,
		[`${pkg.name}/attachments`]: `${dir}/src/attachments/public.d.ts`,
		[`${pkg.name}/compiler`]: `${dir}/src/compiler/public.d.ts`,
		[`${pkg.name}/easing`]: `${dir}/src/easing/index.js`,
		[`${pkg.name}/legacy`]: `${dir}/src/legacy/legacy-client.js`,
		[`${pkg.name}/motion`]: `${dir}/src/motion/public.d.ts`,
		[`${pkg.name}/reactivity`]: `${dir}/src/reactivity/index-client.js`,
		[`${pkg.name}/reactivity/window`]: `${dir}/src/reactivity/window/index.js`,
		[`${pkg.name}/server`]: `${dir}/src/server/index.d.ts`,
		[`${pkg.name}/store`]: `${dir}/src/store/public.d.ts`,
		[`${pkg.name}/transition`]: `${dir}/src/transition/public.d.ts`,
		[`${pkg.name}/events`]: `${dir}/src/events/public.d.ts`,
		[`${pkg.name}/types/compiler/preprocess`]: `${dir}/src/compiler/preprocess/legacy-public.d.ts`,
		[`${pkg.name}/types/compiler/interfaces`]: `${dir}/src/compiler/types/legacy-interfaces.d.ts`
	}
});

// -------------------------------------------------------------
// Alias-safe module forwarding
// -------------------------------------------------------------
const typesPath = `${dir}/types/index.d.ts`;
let types = fs.readFileSync(typesPath, 'utf-8');

// Force module mode (required for TS + alias installs)
if (!types.startsWith('export {}')) {
	types = `export {};\n\n${types}`;
}
fs.writeFileSync(typesPath, types + '\n');

// -------------------------------------------------------------
// Generate a separate TypeScript alias declaration if needed
// -------------------------------------------------------------
const alias = process.env.SVELTE_PACKAGE_ALIAS;

if (alias && alias !== pkg.name) {
	const aliasFilePath = `${dir}/types/alias.d.ts`;
	const aliasContent = `
// This file is auto-generated by generate-types.js
// TypeScript alias support for Svelte package

declare module '${alias}' {
  export * from '${pkg.name}';
}

declare module '${alias}/*' {
  export * from '${pkg.name}/*';
}
`;
	fs.writeFileSync(aliasFilePath, aliasContent.trimStart() + '\n');
	console.log(`✅ Alias declaration file generated at: ${aliasFilePath}`);
}

// -------------------------------------------------------------
// Validation (unchanged)
// -------------------------------------------------------------
const bad_links = [...types.matchAll(/\]\((\/[^)]+)\)/g)];
if (bad_links.length > 0) {
	console.error(
		`The following links in JSDoc annotations should be prefixed with https://svelte.dev:`
	);
	for (const [, link] of bad_links) {
		console.error(`- ${link}`);
	}
	process.exit(1);
}

if (types.includes('\texport { ')) {
	console.error(
		`The generated types file should not contain 'export { ... }' statements. ` +
		`TypeScript is bad at following these...`
	);
	process.exit(1);
}
