/* generated by Svelte vX.Y.Z */
import { addListener, assign, createElement, detachNode, init, insertNode, proto, removeListener, setAttribute } from "svelte/shared.js";

function create_main_fragment(component, ctx) {
	var input, input_updating = false;

	function input_input_handler() {
		input_updating = true;
		component.set({ files: input.files });
		input_updating = false;
	}

	return {
		c() {
			input = createElement("input");
			addListener(input, "input", input_input_handler);
			setAttribute(input, "type", "file");
			input.multiple = true;
		},

		m(target, anchor) {
			insertNode(input, target, anchor);

			input.files = ctx.files;
		},

		p(changed, ctx) {
			if (!input_updating) input.files = ctx.files;
		},

		d(detach) {
			if (detach) {
				detachNode(input);
			}

			removeListener(input, "input", input_input_handler);
		}
	};
}

function SvelteComponent(options) {
	init(this, options);
	this._state = assign({}, options.data);
	this._intro = true;

	this._fragment = create_main_fragment(this, this._state);

	if (options.target) {
		this._fragment.c();
		this._mount(options.target, options.anchor);
	}
}

assign(SvelteComponent.prototype, proto);
export default SvelteComponent;