/* generated by Svelte vX.Y.Z */
import { append, assign, createSvgElement, createText, detachNode, init, insert, noop, proto } from "svelte/shared.js";

function create_main_fragment(component, ctx) {
	var svg, title, text;

	return {
		c() {
			svg = createSvgElement("svg");
			title = createSvgElement("title");
			text = createText("a title");
		},

		m(target, anchor) {
			insert(target, svg, anchor);
			append(svg, title);
			append(title, text);
		},

		p: noop,

		d(detach) {
			if (detach) {
				detachNode(svg);
			}
		}
	};
}

function SvelteComponent(options) {
	init(this, options);
	this._state = assign({}, options.data);
	this._intro = true;

	this._fragment = create_main_fragment(this, this._state);

	if (options.target) {
		this._fragment.c();
		this._mount(options.target, options.anchor);
	}
}

assign(SvelteComponent.prototype, proto);
export default SvelteComponent;