/* generated by Svelte vX.Y.Z */
import { create_ssr_component, debug, each, escape } from "svelte/internal.js";

const SvelteComponent = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
	let { things, foo } = $$props;

	return `${each(things, (thing) => `<span>${escape(thing.name)}</span>
		${debug(null, 2, 2, { foo })}`)}

	<p>foo: ${escape(foo)}</p>`;
});

export default SvelteComponent;