/* generated by Svelte vX.Y.Z-alpha1 */
import { SvelteComponentDev, debug, each, escape } from "svelte/internal.js";

var SvelteComponent = {};

SvelteComponent.render = function(props = {}, options = {}) {
	var components = new Set();

	function addComponent(component) {
		components.add(component);
	}

	var result = { head: '', addComponent };
	var html = SvelteComponent.$$render(result, props, options);

	var cssCode = Array.from(components).map(c => c.css && c.css.code).filter(Boolean).join('\n');

	return {
		html,
		head: result.head,
		css: { code: cssCode, map: null },
		toString() {
			return html;
		}
	};
}

SvelteComponent.$$render = function($$result, ctx, options) {
	$$result.addComponent(SvelteComponent);

	return `${ each(ctx.things, item => Object.assign({}, ctx, { thing: item }), ctx => `<span>${escape(ctx.thing.name)}</span>
		${debug(null, 2, 2, { foo: ctx.foo })}`)}

	<p>foo: ${escape(ctx.foo)}</p>`;
};

SvelteComponent.css = {
	code: '',
	map: null
};

var warned = false;
export default SvelteComponent;