/* generated by Svelte vX.Y.Z */
import { Component, assign, noop } from "svelte/shared.js";

function foo() {
	console.log('foo');
}

function bar() {
	console.log('bar');
}



function create_main_fragment(component, state) {

	return {
		c: noop,

		m: noop,

		p: noop,

		u: noop,

		d: noop
	};
}

class SvelteComponent extends Component {
	constructor(options) {
		super(options);
		this._state = assign({}, options.data);

		this._fragment = create_main_fragment(this, this._state);

		if (options.target) {
			this._fragment.c();
			this._mount(options.target, options.anchor);
		}
	}
}

assign(SvelteComponent.prototype, {
	foo,

	bar: [bar][0]
});
export default SvelteComponent;