/* generated by Svelte vX.Y.Z */
import { assign, createElement, createText, detachNode, init, insertNode, noop, proto } from "svelte/shared.js";

function create_main_fragment(component, ctx) {
	var div, text, div_1, div_1_style_value;

	return {
		c() {
			div = createElement("div");
			text = createText("\n");
			div_1 = createElement("div");
			div.style.cssText = ctx.style;
			div_1.style.cssText = div_1_style_value = "" + ctx.key + ": " + ctx.value;
		},

		m(target, anchor) {
			insertNode(div, target, anchor);
			insertNode(text, target, anchor);
			insertNode(div_1, target, anchor);
		},

		p(changed, ctx) {
			if (changed.style) {
				div.style.cssText = ctx.style;
			}

			if ((changed.key || changed.value) && div_1_style_value !== (div_1_style_value = "" + ctx.key + ": " + ctx.value)) {
				div_1.style.cssText = div_1_style_value;
			}
		},

		u() {
			detachNode(div);
			detachNode(text);
			detachNode(div_1);
		},

		d: noop
	};
}

function SvelteComponent(options) {
	init(this, options);
	this._state = assign({}, options.data);

	this._fragment = create_main_fragment(this, this._state);

	if (options.target) {
		this._fragment.c();
		this._mount(options.target, options.anchor);
	}
}

assign(SvelteComponent.prototype, proto);
export default SvelteComponent;