/* generated by Svelte vX.Y.Z */
import { Component, assign, createElement, detachNode, insertNode, noop, setInputType } from "svelte/shared.js";

function create_main_fragment(component, state) {
	var input;

	return {
		c: function create() {
			input = createElement("input");
			this.h();
		},

		h: function hydrate() {
			setInputType(input, "search");
		},

		m: function mount(target, anchor) {
			insertNode(input, target, anchor);
		},

		p: noop,

		u: function unmount() {
			detachNode(input);
		},

		d: noop
	};
}

class SvelteComponent extends Component {
	constructor(options) {
		super(options);
		this._state = assign({}, options.data);

		this._fragment = create_main_fragment(this, this._state);

		if (options.target) {
			this._fragment.c();
			this._mount(options.target, options.anchor);
		}
	}
}
export default SvelteComponent;