/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	assign,
	bubble,
	detach,
	element,
	empty,
	get_spread_update,
	init,
	insert,
	listen,
	noop,
	safe_not_equal,
	set_attributes,
	set_custom_element_data_map
} from "svelte/internal";

function create_dynamic_element(ctx) {
	let svelte_element;
	let mounted;
	let dispose;
	let svelte_element_levels = [{ class: "some-classname" }];
	let svelte_element_data = {};

	for (let i = 0; i < svelte_element_levels.length; i += 1) {
		svelte_element_data = assign(svelte_element_data, svelte_element_levels[i]);
	}

	return {
		c() {
			svelte_element = element("a");
			svelte_element.textContent = "Hi";

			if ((/-/).test("a")) {
				set_custom_element_data_map(svelte_element, svelte_element_data);
			} else {
				set_attributes(svelte_element, svelte_element_data);
			}
		},
		m(target, anchor) {
			insert(target, svelte_element, anchor);

			if (!mounted) {
				dispose = listen(svelte_element, "keydown", /*keydown_handler*/ ctx[0]);
				mounted = true;
			}
		},
		p(ctx, dirty) {
			svelte_element_data = get_spread_update(svelte_element_levels, [{ class: "some-classname" }]);

			if ((/-/).test("a")) {
				set_custom_element_data_map(svelte_element, svelte_element_data);
			} else {
				set_attributes(svelte_element, svelte_element_data);
			}
		},
		d(detaching) {
			if (detaching) detach(svelte_element);
			mounted = false;
			dispose();
		}
	};
}

function create_fragment(ctx) {
	let previous_tag = "a";
	let svelte_element_anchor;
	let svelte_element = "a" && create_dynamic_element(ctx);

	return {
		c() {
			if (svelte_element) svelte_element.c();
			svelte_element_anchor = empty();
		},
		m(target, anchor) {
			if (svelte_element) svelte_element.m(target, anchor);
			insert(target, svelte_element_anchor, anchor);
		},
		p(ctx, [dirty]) {
			if ("a") {
				if (!previous_tag) {
					svelte_element = create_dynamic_element(ctx);
					svelte_element.c();
					svelte_element.m(svelte_element_anchor.parentNode, svelte_element_anchor);
				} else if (safe_not_equal(previous_tag, "a")) {
					svelte_element.d(1);
					svelte_element = create_dynamic_element(ctx);
					svelte_element.c();
					svelte_element.m(svelte_element_anchor.parentNode, svelte_element_anchor);
				} else {
					svelte_element.p(ctx, dirty);
				}
			} else if (previous_tag) {
				svelte_element.d(1);
				svelte_element = null;
			}

			previous_tag = "a";
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(svelte_element_anchor);
			if (svelte_element) svelte_element.d(detaching);
		}
	};
}

function instance($$self) {
	function keydown_handler(event) {
		bubble.call(this, $$self, event);
	}

	return [keydown_handler];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default Component;