/* generated by Svelte vX.Y.Z-alpha1 */
import { SvelteComponent as SvelteComponent_1, addListener, createElement, detachNode, flush, init, insert, noop, removeListener, run, safe_not_equal } from "svelte/internal.js";

function handleFoo(bar) {
	console.log(bar);
}

function create_fragment(component, ctx) {
	var button, current;

	return {
		c() {
			button = createElement("button");
			button.textContent = "foo";
			addListener(button, "foo", ctx.foo_handler);
		},

		m(target, anchor) {
			insert(target, button, anchor);
			current = true;
		},

		p: noop,

		i(target, anchor) {
			if (current) return;
			this.m(target, anchor);
		},

		o: run,

		d(detach) {
			if (detach) {
				detachNode(button);
			}

			removeListener(button, "foo", ctx.foo_handler);
		}
	};
}

function define($$self, $$props) {
	let { bar } = $$props;

	function foo(node, callback) {
		// code goes here
	}

	function foo_handler() {
		return handleFoo(bar);
	}

	// TODO only what's needed by the template
	$$self.$$.get = () => ({ bar, foo_handler });

	$$self.$$.set = $$props => {
		if ('bar' in $$props) bar = $$props.bar;
	};
}

class SvelteComponent extends SvelteComponent_1 {
	constructor(options) {
		super();
		init(this, options, define, create_fragment, safe_not_equal);
	}

	get bar() {
		return this.$$.get().bar;
	}

	set bar(value) {
		this.$set({ bar: value });
		flush();
	}
}
export default SvelteComponent;