/* generated by Svelte vX.Y.Z */
import { append, assign, createElement, detachNode, init, insert, noop, proto } from "svelte/shared.js";

function add_css() {
	var style = createElement("style");
	style.id = 'svelte-1slhpfn-style';
	style.textContent = "@media(min-width: 1px){div.svelte-1slhpfn{color:red}}";
	append(document.head, style);
}

function create_main_fragment(component, ctx) {
	var div;

	return {
		c() {
			div = createElement("div");
			div.className = "svelte-1slhpfn";
		},

		m(target, anchor) {
			insert(target, div, anchor);
		},

		p: noop,

		d(detach) {
			if (detach) {
				detachNode(div);
			}
		}
	};
}

function SvelteComponent(options) {
	init(this, options);
	this._state = assign({}, options.data);
	this._intro = true;

	if (!document.getElementById("svelte-1slhpfn-style")) add_css();

	this._fragment = create_main_fragment(this, this._state);

	if (options.target) {
		this._fragment.c();
		this._mount(options.target, options.anchor);
	}
}

assign(SvelteComponent.prototype, proto);
export default SvelteComponent;