/* generated by Svelte vX.Y.Z */
import { SvelteComponent as SvelteComponent_1, createText, detachNode, init, insert, mount_component, noop, safe_not_equal } from "svelte/internal";
import Imported from "Imported.svelte";

function create_fragment(ctx) {
	var text, current;

	var imported = new Imported({});

	var nonimported = new NonImported({});

	return {
		c() {
			imported.$$.fragment.c();
			text = createText("\n");
			nonimported.$$.fragment.c();
		},

		m(target, anchor) {
			mount_component(imported, target, anchor);
			insert(target, text, anchor);
			mount_component(nonimported, target, anchor);
			current = true;
		},

		p: noop,

		i(local) {
			if (current) return;
			imported.$$.fragment.i(local);

			nonimported.$$.fragment.i(local);

			current = true;
		},

		o(local) {
			imported.$$.fragment.o(local);
			nonimported.$$.fragment.o(local);
			current = false;
		},

		d(detach) {
			imported.$destroy(detach);

			if (detach) {
				detachNode(text);
			}

			nonimported.$destroy(detach);
		}
	};
}

class SvelteComponent extends SvelteComponent_1 {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal);
	}
}

export default SvelteComponent;