/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	detach,
	init,
	insert,
	mount_component,
	noop,
	safe_not_equal,
	space
} from "svelte/internal";
import Imported from "Imported.svelte";

function create_fragment(ctx) {
	var t, current;

	var imported = new Imported({});

	var nonimported = new NonImported({});

	return {
		c() {
			imported.$$.fragment.c();
			t = space();
			nonimported.$$.fragment.c();
		},

		m(target, anchor) {
			mount_component(imported, target, anchor);
			insert(target, t, anchor);
			mount_component(nonimported, target, anchor);
			current = true;
		},

		p: noop,

		i(local) {
			if (current) return;
			imported.$$.fragment.i(local);

			nonimported.$$.fragment.i(local);

			current = true;
		},

		o(local) {
			imported.$$.fragment.o(local);
			nonimported.$$.fragment.o(local);
			current = false;
		},

		d(detaching) {
			imported.$destroy(detaching);

			if (detaching) {
				detach(t);
			}

			nonimported.$destroy(detaching);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, []);
	}
}

export default Component;