/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	append,
	create_animation,
	create_each_blocks,
	destroy_each_blocks,
	detach,
	element,
	empty,
	fix_and_destroy_block,
	fix_position,
	init,
	init_each_block,
	insert,
	mount_each_blocks,
	noop,
	safe_not_equal,
	set_data,
	text,
	update_keyed_each
} from "svelte/internal";

function get_each_context(ctx, list, i) {
	const child_ctx = Object.create(ctx);
	child_ctx.thing = list[i];
	return child_ctx;
}

// (19:0) {#each things as thing (thing.id)}
function create_each_block(ctx, key_1) {
	var div, t_value = ctx.thing.name + "", t, rect, stop_animation = noop;

	return {
		key: key_1,

		first: null,

		c() {
			div = element("div");
			t = text(t_value);
			this.first = div;
		},

		m(target, anchor) {
			insert(target, div, anchor);
			append(div, t);
		},

		p(changed, ctx) {
			if ((changed.things) && t_value !== (t_value = ctx.thing.name + "")) {
				set_data(t, t_value);
			}
		},

		r() {
			rect = div.getBoundingClientRect();
		},

		f() {
			fix_position(div);
			stop_animation();
		},

		a() {
			stop_animation();
			stop_animation = create_animation(div, rect, foo, {});
		},

		d(detaching) {
			if (detaching) {
				detach(div);
			}
		}
	};
}

function create_fragment(ctx) {
	var each_1_anchor;

	let each_value = ctx.things;

	let each_blocks = init_each_block(
		ctx,
		get_each_context,
		ctx => ctx.things,
		ctx => ctx.thing.id,
		create_each_block,
		null
	);

	return {
		c() {
			create_each_blocks(each_blocks);

			each_1_anchor = empty();
		},

		m(target, anchor) {
			mount_each_blocks(each_blocks, target, anchor);

			insert(target, each_1_anchor, anchor);
		},

		p(changed, ctx) {
			const each_value = ctx.things;
			for (let i = 0; i < each_blocks.b.length; i += 1) each_blocks.b[i].r();
			update_keyed_each(
				each_blocks,
				changed,
				1,
				ctx,
				each_1_anchor.parentNode,
				fix_and_destroy_block,
				each_1_anchor
			);
			for (let i = 0; i < each_blocks.b.length; i += 1) each_blocks.b[i].a();
		},

		i: noop,
		o: noop,

		d(detaching) {
			destroy_each_blocks(each_blocks, detaching);

			if (detaching) {
				detach(each_1_anchor);
			}
		}
	};
}

function foo(node, animation, params) {
	const dx = animation.from.left - animation.to.left;
	const dy = animation.from.top - animation.to.top;

	return {
		delay: params.delay,
		duration: 100,
		tick: (t, u) => {
			node.dx = u * dx;
			node.dy = u * dy;
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { things } = $$props;

	$$self.$set = $$props => {
		if ('things' in $$props) $$invalidate('things', things = $$props.things);
	};

	return { things };
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, ["things"]);
	}
}

export default Component;