/* generated by Svelte vX.Y.Z */
import {
	SvelteComponent,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal,
	set_style,
	space
} from "svelte/internal";

function create_fragment(ctx) {
	let div0;
	let t;
	let div1;

	return {
		c() {
			div0 = element("div");
			t = space();
			div1 = element("div");
			set_style(div0, "background", "url(data:image/png;base64," + /*data*/ ctx[0] + ")");
			set_style(div1, "background", "url(data:image/png;base64," + /*data*/ ctx[0] + ")");
		},
		m(target, anchor) {
			insert(target, div0, anchor);
			insert(target, t, anchor);
			insert(target, div1, anchor);
		},
		p(ctx, [dirty]) {
			if (dirty & /*data*/ 1) {
				set_style(div0, "background", "url(data:image/png;base64," + /*data*/ ctx[0] + ")");
			}

			if (dirty & /*data*/ 1) {
				set_style(div1, "background", "url(data:image/png;base64," + /*data*/ ctx[0] + ")");
			}
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(div0);
			if (detaching) detach(t);
			if (detaching) detach(div1);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { data } = $$props;

	$$self.$$set = $$props => {
		if ("data" in $$props) $$invalidate(0, data = $$props.data);
	};

	return [data];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { data: 0 });
	}
}

export default Component;