/* This file is generated by scripts/process-messages/index.js. Do not edit! */

import { DEV } from 'esm-env';

var bold = 'font-weight: bold';
var normal = 'font-weight: normal';

/**
 * `<svelte:element this="%tag%">` is a void element — it cannot have content
 * @param {string} tag
 */
export function dynamic_void_element_content(tag) {
	if (DEV) {
		console.warn(`%c[svelte] dynamic_void_element_content\n%c\`<svelte:element this="${tag}">\` is a void element — it cannot have content`, bold, normal);
	} else {
		// TODO print a link to the documentation
		console.warn("dynamic_void_element_content");
	}
}

/**
 * An object could not be cloned with $state.snapshot, the original value will be returned
 */
export function state_snapshot_uncloneable() {
	if (DEV) {
		console.warn(`%c[svelte] state_snapshot_uncloneable\n%cAn object could not be cloned with $state.snapshot, the original value will be returned`, bold, normal);
	} else {
		// TODO print a link to the documentation
		console.warn("state_snapshot_uncloneable");
	}
}